fix broken celery dependency
Newly pushed version of 'vine' breaks our version
of 'celery' package:

   File "/usr/local/envs/FragMAX/lib/python3.6/site-packages/celery/local.py", line 17, in <module>
    from .five import PY3, bytes_if_py2, items, string, string_t
  File "/usr/local/envs/FragMAX/lib/python3.6/site-packages/celery/five.py", line 7, in <module>
    import vine.five
ModuleNotFoundError: No module named 'vine.five'

Upgrading 'celery' to a newer release solves the issue.